### ISSUE TITLE
Cannot get extension working - Am I using the wrong API Keys?

### ISSUE THREAD

**Issue by ahandsel** [yokawasa/vscode-translator-voice#4] opened 2021-01-07 10:15 UTC
Hello Yokawasa,

Thank you for creating this cool VS Code Extension!
I am trying to use it however I only get the `Translating your text: Target Language (en)` message when running the `TranslatorVoice: Translate` command. This is of course even after inputting my API Subscription Keys.

Thus, I wanted to verify that I have correctly configured your Extension.

For `Translatorvoice: Sub Key Translator`, I am using Microsoft's `Translator` offered under Microsoft Azure's Marketplace. I followed [How to sign up for Translator](https://docs.microsoft.com/en-us/azure/cognitive-services/translator/translator-how-to-signup) help doc

**Comment by yokawasa** [comment] 2021-01-10 06:10
Hello @ahandsel 
Very sorry for the late response

If you have right subscription key, and set it to Translatorvoice: Sub Key Translator correctly, you will see the translated text in Output like this

<img width="1264" alt="Screen Shot 2021-01-10 at 14 56 16" src="https://user-images.githubusercontent.com/82332/104115658-d4f33900-5354-11eb-9514-18648065577e.png">

I guess your sub key is not valid one.

Here is how you get Sub Key for Translator (Azure Cognitive Services )

After signing in to the Azure portal, you can create a subscription key for Translator Text API access in the following ways:

1. Select "+ Create Resource" (+ リソースの作成) .
2. In the Search Marketplace search box, type ”Translator Text” and select Translator Text from the results.
3. Select ”Create”（作成） to define the subscription details.
4. On the subscription details page, select "price level"（価格レベル） that suits your needs from the Price Level list and click Create to complete the subscription creation.
  - Each subscription has a Free level. The Free level has the same features as the paid plan and has no expiration date.
  - You can only have one free subscription in your account.
5. Once you have created a subscription to the Translator Text API, get a subscription key for your API.

Sorry the image below are Japanease one

<img width="1639" alt="get-translator-api-subscription-key" src="https://user-images.githubusercontent.com/82332/104115683-20a5e280-5355-11eb-972e-db38ca4b94bd.png">

Plase try with right sub key and let me know if you still have a problem.

**Comment by ahandsel** [comment] 2021-01-10 14:41
@yokawasa Thank you for your quick response! I appreciate the steps & screenshots!

I went through and created an API for Translator Text and inputted that into your VS Code Extension setting but it still does not work.

Tested out my API Key using the [Translator V3.0 Reference - Azure Cognitive Services](https://docs.microsoft.com/en-us/azure/cognitive-services/translator/reference/v3-0-reference) Doc and was successful.

I also generated an `access token` and tried that as well but still did not work.

Here is what I have tried. Sorry for the ugly URL block ( ^ . ^ ;)

https://youtu.be/_dAQy-jg1Nc

Thank you for your time!

**Comment by yokawasa** [comment] 2021-01-10 22:08
@ahandsel Thank you for the confirmation.
In your youtube video, I saw multiple `TranslatorVoice` output channel like this. To clarify the problem, can you please check if translated output came out at the bottom channel? 
<img width="1081" alt="Screen Shot 2021-01-11 at 6 50 12" src="https://user-images.githubusercontent.com/82332/104136654-e2eb9d00-53da-11eb-8dd7-75cd3395db8a.png">

Anyway, I'll improve the extension not to make multiple TranslatorVoice ouput in the next version.

**Comment by yokawasa** [comment] 2021-01-11 09:07
@ahandsel 
> Anyway, I'll improve the extension not to make multiple TranslatorVoice ouput in the next version.

By the way, I've fixed this. Please upgrade the extension to the latest version, v0.5.0
https://github.com/yokawasa/vscode-translator-voice/releases/tag/0.5.0

Thank you

**Comment by yokawasa** [comment] 2021-01-17 07:51
@ahandsel Can you please try the latest version (v0.5.0) and check if the issue is resolved?

**Comment by yokawasa** [comment] 2021-06-13 15:45
I'm closing the issue, but if you need further help, feel free to open another issue
thanks

**Closed as completed by yokawasa** 2021-06-13 15:45 UTC
